### ISSUE TITLE
[2kki] Viewing the Badge Gallery of an user using the AUTO Menu Theme 30 "Nuaah's_menu" does not display correctly

### ISSUE THREAD

**Issue by Mimigris** [ynoproject/forest-orb#200]
![image](https://user-images.githubusercontent.com/108797333/194715518-d7042618-ca44-4688-9e8d-e1b1d7d3ae34.png)

**Comment by Flashfyre** [comment]
Fixed in https://github.com/ynoproject/forest-orb/pull/208
