### ISSUE TITLE
Website rules for chatting and playing

### ISSUE THREAD

**Issue by Ayayayaa** [ynoproject/forest-orb#213]
I think it's really important that we have rules on the website and not just on the Discord server. For chatting rules, the same ones as the server's rules minus Discord-exclusive stuff; And also, rules regarding the game such as debug mode and cheating (obviously) being forbidden. One last thing, considering having a rule on new content being spoilered when discussed in chat, at least for a week after its release? Though not everyone might have the same opinion on it

**Comment by notdistorted** [comment]
Current plan:
* Internal review on the draft of the game rules
Implementation:
* Display the rule modal Twitch-style, initial click on the text input triggers that, and a control for access to the rules appears afterwards
