### ISSUE TITLE
Tapping the viewport on iOS will cause the game to crash

### ISSUE THREAD

**Issue by vassembly** [ynoproject/forest-orb#305]
The game freezes almost instantly and stops handling any input.

![image](https://github.com/ynoproject/forest-orb/assets/53514993/1612e970-4bf5-4b6e-bfcc-d17fc2bf721f)

Console doesn't seem helpful at all.

![image](https://github.com/ynoproject/forest-orb/assets/53514993/f9f2ac5e-ad51-4701-8da7-635a2e660f70)

**Comment by X64X32** [comment]
I'm using iOS 17 beta 3. Not sure if that was an issue on 16.

**Comment by Desdaemon** [comment]
Might be an issue with the engine. The same problem can be observed on https://easyrpg.org/play (build 2023-04-29), but not on https://easyrpg.org/play/master.
