### ISSUE TITLE
The location of 2kki badges is displayed as Unknown Location when the entry is not in the config while playing another game

### ISSUE THREAD

**Issue by Mimigris** [ynoproject/forest-orb#425]
If you are playing on another game than Yume 2kki and that you check the location of a 2kki badge and that said location is not in ynolocations, the entry will be displayed as Unknown Location since the Map IDs pages of the wiki are not fetched while playing another game.
![image](https://github.com/ynoproject/forest-orb/assets/108797333/aae7ee8d-e288-4d5f-90bc-0c0fb09b9934)

**Comment by Desdaemon** [comment]
With the changes in #455 and #462, badges now sometimes show "Querying Location..." due to a possible race condition between updating the UI and fetching the locations.
