### ISSUE TITLE
Issues with the Time Trial help text

### ISSUE THREAD

**Issue by krossower1** [ynoproject/forest-orb#448]
1. The help text doesn't display even though the icon and it's contents are intact.
2. The icon for displaying help text doesn't appear in the English UI.

I've looked at these things for a few hours and I didn't find anything wrong, maybe I don't understand the structure of the site enough or some of the features it uses.

**Comment by Desdaemon** [comment]
I've made the Time Trial popup visible in the badge modal in #462, but for future reference one can apply i18n strings like this: https://github.com/ynoproject/forest-orb/blob/9465a0e680d5c235a2e369db7d6607b02302ea07/badges.js#L348-L355
