### ISSUE TITLE
Sporadic issues with language detection

### ISSUE THREAD

**Issue by krossower1** [ynoproject/forest-orb#510]
I know an issue like this is already public, but this one doesn't depend on if the language selected exists. With the website set to English, sometimes (commonly 1st launch per day?) the game starts in Japanese- makes me think the game is failing to read the language in these edge cases. The circumstances indicate to me that it may have to do with differences in loading times.

**Comment by Desdaemon** [comment]
I've noticed that refreshing without cache usually leads to this issue, not sure if that's a good place to start looking.

**Comment by Mimigris** [comment]
Kinda duplicate with #414 : I originally created code to detect if the selected language has an ingame translation or not (which was partially broken due to having no idea how to code), could be related to that, otherwise it's an issue with how the entire feature works.
